# Generated by Django 3.1.1 on 2020-09-13 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('send_date', models.DateTimeField(default=datetime.datetime(2020, 9, 13, 5, 24, 50, 811149, tzinfo=utc))),
            ],
        ),
    ]
