# Generated by Django 3.1.1 on 2020-09-13 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactemail',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
