# Generated by Django 3.1.1 on 2020-09-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200913_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactemail',
            old_name='useremail',
            new_name='email',
        ),
    ]
